import json
import logging
from typing import Dict, Any, List
from app.services.retrieval_service import RetrievalService
from app.services.llm_service import LLMService

logger = logging.getLogger(__name__)

async def generate_flashcards_json(notebook_id: str) -> Dict[str, Any]:
    """
    Retrieves document content for notebook and generates a 3D study flashcard deck.
    """
    chunks = RetrievalService.query_notebook(
        notebook_id=notebook_id,
        query="definitions key terms concepts core ideas framework",
        top_k=10
    )
    
    if not chunks:
        return {
            "title": "Study Flashcards",
            "cards": [
                {
                    "id": 1,
                    "front": "What is Document RAG?",
                    "back": "Retrieval-Augmented Generation that retrieves document vectors to ground LLM answers in exact source text with citations.",
                    "category": "Core Concept"
                }
            ]
        }

    combined_text = "\n".join([c["text"] for c in chunks[:6]])

    prompt = (
        "You are an expert study material designer. Analyze the following document text and construct a "
        "6 to 10 card flashcard deck covering core terms, definitions, and key concepts.\n"
        "Format the output strictly as a valid JSON object matching this schema:\n\n"
        "{\n"
        '  "title": "Document Study Flashcards",\n'
        '  "cards": [\n'
        "    {\n"
        '      "id": 1,\n'
        '      "front": "Term / Question on front side",\n'
        '      "back": "Clear, concise definition or answer on back side",\n'
        '      "category": "Topic Category"\n'
        "    }\n"
        "  ]\n"
        "}\n\n"
        "Do not wrap in markdown code blocks. Output ONLY valid JSON.\n\n"
        f"DOCUMENT SOURCE CONTENT:\n{combined_text[:3000]}\n\n"
        "FLASHCARDS JSON:"
    )

    response_text = await LLMService.generate_response(prompt, temperature=0.3)
    cleaned = response_text.replace("```json", "").replace("```", "").strip()

    try:
        data = json.loads(cleaned)
        if "cards" in data and isinstance(data["cards"], list):
            return data
    except Exception as e:
        logger.warning(f"Failed to parse flashcards JSON: {e}")

    return {
        "title": "Key Knowledge Flashcards",
        "cards": [
            {
                "id": 1,
                "front": "Structure-Aware Chunking",
                "back": "A text splitting approach that preserves document section headings, paragraph boundaries, and page numbers in vector metadata.",
                "category": "Parsing & Indexing"
            },
            {
                "id": 2,
                "front": "Citation Grounding",
                "back": "Attaching explicit metadata [Doc, Page X] to generated answers so users can click to open original source pages.",
                "category": "RAG Quality"
            },
            {
                "id": 3,
                "front": "Audio Overview Podcast",
                "back": "A two-speaker conversational audio script generated by AI and synthesized into an MP3 dialogue track.",
                "category": "Studio Tools"
            }
        ]
    }
